updateChecker: false

join_message:
  # Set the default message without player head.
  default_message: "&fWelcome &c%player_name% &fto the server!"

  # useMargin is a style for the message making a margin top & bottom of the message.
  use_margin: true

  # If it's false it show a normal message.
  # But if it's True it shows the player head in chat.
  player_head_join_message: true

  # The message support PlaceholderAPI & Minecraft chat colors.
  message_content:
    - ""
    - "&fWelcome &c%player_name% &fto the server!"
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""

hooks:
  enabled: false
  discord_hook_url: ""
  thumbnail_player_head: true
  # We don't support the timestamp prop from discord web hook.
  # We support PlaceholderAPI in values like %player_name%
  # Discord hook config file is inside /hook/discord.json
  # You can create your own here: https://discohook.org/

  # Here is the discord.ico:
  # https://cdn.prod.website-files.com/6257adef93867e50d84d30e2/6266bc493fb42d4e27bb8393_847541504914fd33810e70a0ea73177e.ico

# All the messages support chat color by &
translation:
  error_permission: "&fYou don't have enough permissions."
  reload_command: "&fThe plugin was reloaded."
  loading_config: "&fLoading configuration..."